### ISSUE TITLE
slow azure blob upload with the powershell action

### ISSUE THREAD

**Issue by freddyrios** [Azure/powershell#31] opened 2021-03-18 14:18 UTC
Hi,

Uploading 3 small files (< 15 KB each) to an azure blob using the powershell action takes 3 minutes. For comparison, uploading the same files into a github release takes 1 second.

I am running something like this:
```
    - name: Publish to Azure blob
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $context = New-AzStorageContext -StorageAccountName myaccount -SasToken "${{secrets.azureBlobQuerystring}}"
          Set-AzStorageBlobContent -File First.zip -Container mycontainer -Context $context.Context -Force
          Set-AzStorageBlobContent -File Second.zip -Container mycontainer -Context $context.Context -Force
          Set-AzStorageBlobContent -File Third.zip -Container mycontainer -Context $context.Context -Force
        azPSVersion: '3.1.0'
```

The above skips the login action since it uses a write only SaS token as we need to limit the access given in this repository. The length of the files as reported in the log by the powershell action are: 13278, 10807, 9747.

Is it expected? Is there any alternate way of running the action that avoids that? Should I use the cli action or even the rest API directly to upload the small files instead?

**Comment by freddyrios** [comment] 2021-03-24 21:40
The problem with the azure action is worse, as depending on the run it can take much longer. I have 2 recent builds where one took 11 minutes and the other one 17, with no errors involved.

After hitting one of those 2 builds I have just moved to the rest API directly instead. Now its takes 1-2 seconds to publish all 3 files.

This is what I used:
```
curl -X PUT -H "x-ms-version: 2020-04-08" -H "Content-Type: application/octet-stream" -H "x-ms-blob-type: BlockBlob" \
  "https://myaccount.blob.core.windows.net/mycontainer/First.zip${{secrets.azureBlobQuerystring}}" \
  --data '@First.zip'

```

**Comment by freddyrios** [comment] 2021-03-25 10:07
The code shared earlier was uploading something but the zip was broken on downloads, here is the correct version / which is functionally correct and still takes 2 seconds:

```
- name: Publish to Azure blob
  run: |
    curl -X PUT -H "x-ms-version: 2020-04-08" -H "Content-Type: application/octet-stream" -H "x-ms-blob-type: BlockBlob" \
      "https://myaccount.blob.core.windows.net/mycontainer/First.zip${{secrets.azureBlobQuerystring}}" \
      --upload-file 'First.zip'
    curl -X PUT -H "x-ms-version: 2020-04-08" -H "Content-Type: application/octet-stream" -H "x-ms-blob-type: BlockBlob" \
      "https://myaccount.blob.core.windows.net/mycontainer/Second.zip${{secrets.azureBlobQuerystring}}" \
      --upload-file 'Second.zip'
    curl -X PUT -H "x-ms-version: 2020-04-08" -H "Content-Type: application/octet-stream" -H "x-ms-blob-type: BlockBlob" \
      "https://myaccount.blob.core.windows.net/mycontainer/Third.zip${{secrets.azureBlobQuerystring}}" \
      --upload-file 'Third.zip'

```

**Comment by BALAGA-GAYATRI** [comment] 2021-09-13 13:56
@freddyrios Assuming that the issue is fixed, closing this. Feel free to reopen incase the issue persists.

**Comment by freddyrios** [comment] 2021-09-14 12:02
@BALAGA-GAYATRI the only reason this no longer affects me is *because I no longer use the powershell action*. Instead I use the rest API directly like stated above.

I would say this bug is as critical was it gets, as anybody running ending in this ticket while looking a solution to this issue will stop using the product i.e. the powershell action.

**Comment by freddyrios** [comment] 2021-09-14 12:05
By the way, if that is no reason enough, think about the perception users get of Azure when they think uploading tiny blob files take 3 minutes. When in reality is the powershell action doing so.

**Comment by BALAGA-GAYATRI** [comment] 2021-09-15 04:54
hey @freddyrios the workaround with apis was misunderstood for solution. This issue is reopened and will be investigated.

**Comment by BALAGA-GAYATRI** [comment] 2021-09-20 09:36
Hey @freddyrios when I use this with `azure/login@v1` action with `enable-AzPSSession: true ` and then executing powershell script for file upload takes 6s (3 files 6KB each). You can consider login action if you are looking for reducing the upload time. 
For your reference - 
1. [workflow file](https://github.com/BALAGA-GAYATRI/pstest/blob/main/.github/workflows/pstest-storage.yml)
2. [workflow run](https://github.com/BALAGA-GAYATRI/pstest/runs/3650042947?check_suite_focus=true)
Let us know if this helps.

**Comment by freddyrios** [comment] 2021-09-20 11:50
hi @BALAGA-GAYATRI, we are using a sas token to limit the level of azure access we are giving to authors working on that repository and its workflow.

If this issue only triggers when using sas tokens instead of an account login, then perhaps our use case isn't very common. 

For our specific case the trade off of keeping our advanced scenario by going to the rest API is reasonable.

**Comment by BALAGA-GAYATRI** [comment] 2021-09-21 05:40
hey @freddyrios If scope of the access is the concern, we use azure service principal credentials where the scope of the access can be restricted to access any particular resource / resource-group / subscription. 
Visit [login action readme](https://github.com/Azure/login#configure-deployment-credentials) for the rbac command used in generating credentials and visit [scopes doc](https://docs.microsoft.com/en-us/azure/role-based-access-control/scope-overview) for understanding on setting scopes in the above command.

**Comment by freddyrios** [comment] 2021-09-21 12:03
@BALAGA-GAYATRI thanks for sharing that. When we have another reason to change that workflow, we will give it a try / closer look.

I am ok to close it, given the issue only happens when using sas tokens instead of azure service principals, so people have 2 options:
1. use azure service principals / azure active directory instead of sas tokens
2. use the rest API (if not possible to use the above)

**Closed** 2021-09-21 12:49 UTC
Labels: performance-issue
