### ISSUE TITLE
Add script file execution support

### ISSUE THREAD

**Issue by Satak** [Azure/powershell#15] opened 2020-09-22 11:20 UTC
Currently only way to run Powershell script is to add the script as inline inside the yaml file. This can be very messy in bigger scripts. Add support to execute Powershell script file from the current repository.

Example:

```yaml
on: [push]

name: AzurePowerShellSample

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        scriptFile: ./my-script.ps1
```

**Comment by aksm-ms** [comment] 2020-09-25 07:45
@Satak Thanks for the suggestion. I will mark this as an enhancement and we will work on it.

**Comment by JAlvarezMSI** [comment] 2020-10-23 20:32
Has there been update to this enhancement because it would be especially useful?

**Comment by marvinbuss** [comment] 2020-11-30 13:44
@aksm-ms Any updates on this? Looks like this Action is still far behind the Azure DevOps solution. Any plans to support this request?

**Comment by marvinbuss** [comment] 2020-12-16 09:40
@aksm-ms @N-Usha @AmrutaKawade I anyone working on this? Any updates?

**Comment by saikiran-karumuri-by** [comment] 2021-01-13 23:51
you can run script like this - 
- name: Run Azure PowerShell script
   uses: azure/powershell@v1
   with:
       inlineScript: |
            ./folderpath/test.ps1
       azPSVersion: '3.1.0'

**Comment by N-Usha** [comment] 2021-02-02 03:13
@marvinbuss - Can you please confirm if the above workaround mentioned by @saikiran-karumuri-by  would work for you?

**Comment by marvinbuss** [comment] 2021-03-01 07:26
I can confirm that it works.

**Comment by kaverma** [comment] 2021-03-12 05:17
Hi @marvinbuss, did you get a chance to check if the above workaround works, can you please confirm?

**Comment by marvinbuss** [comment] 2021-03-12 06:18
> Hi @marvinbuss, did you get a chance to check if the above workaround works, can you please confirm?

Yes, it works. See my comment above.

**Comment by kaverma** [comment] 2021-03-12 09:40
> > Hi @marvinbuss, did you get a chance to check if the above workaround works, can you please confirm?
> 
> Yes, it works. See my comment above.

OK, great, thanks!

**Comment by kaverma** [comment] 2021-03-17 03:47
> you can run script like this -
> 
> * name: Run Azure PowerShell script
>   uses: azure/powershell@v1
>   with:
>   inlineScript: |
>   ./folderpath/test.ps1
>   azPSVersion: '3.1.0'

Closing this issue as the script can be run like mentioned above

**Closed by kaverma** 2021-03-17 03:47 UTC
Labels: enhancement

**Comment by lmrisdal** [comment] 2021-05-28 15:00
Reopening this. Is it possible to supply script parameters to the powershell script file? I have two parameters defined in my script that I would like to to use.
